#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/bd57fd27-b154-4950-baa3-dbd4c9ddb1ea

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float rmsValue;
  bool btn2;
  bool btn1;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <ArduinoGraphics.h> // Arduino_MKRRGB depends on ArduinoGraphics
#include <Arduino_MKRRGB.h>

#define btn1OUT 6
#define btn2OUT 7

bool btn1_state = false;
bool btn2_state = false;


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();


  pinMode(btn1OUT, OUTPUT);
  pinMode(btn2OUT, OUTPUT);

  //analogWriteResolution()

}

void loop() {
  ArduinoCloud.update();
  // Your code here
  float rmsValueTmp = 0.0;
  rmsValueTmp = analogRead(A0);
  rmsValue = (float)map(rmsValueTmp, 500, 1023, 0, 300) / 1023.0 * 3.3;
}


void onRmsValueChange() {
}

void onBtn2Change() {
  digitalWrite(btn1OUT, btn1);
}

void onBtn1Change() {
  digitalWrite(btn2OUT, btn2);
}


