// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "bd57fd27-b154-4950-baa3-dbd4c9ddb1ea";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onRmsValueChange();
void onBtn2Change();
void onBtn1Change();

float rmsValue;
bool btn2;
bool btn1;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(rmsValue, READWRITE, ON_CHANGE, onRmsValueChange);
  ArduinoCloud.addProperty(btn2, READWRITE, 1 * SECONDS, onBtn2Change);
  ArduinoCloud.addProperty(btn1, READWRITE, 1 * SECONDS, onBtn1Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
